import type { Metadata } from "next";
import "./styles/globals.css";

export const metadata: Metadata = {
  title: "USER Pablo",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
